### ISSUE TITLE
[emu-10-x86_64] ./mach bootstrap is broken

### ISSUE THREAD

**Issue by lissyx** [kaiostech/gecko-b2g#10]
Fails on fetching several taskcluster-built:
 - `linux64-node`
 - `linux64-minidump-stackwalk`

**Comment by lissyx** [comment]
We also have issues because:
 - there is no `level-3` index on taskcluster for kaios
 - forcing `MOZ_SCM_LEVEL=2` there is no index on taskcluster for some of the artifacts (linux64-minidump-stackwalk)

**Comment by lissyx** [comment]
When debugging, I see an hash: `index.gecko.cache.level-3.toolchains.v3.linux64-minidump-stackwalk.hash.0b4f2e00afc8d5325a9ee8b6a5797585aa4d60bf058fa8b8c96fd6323e6541e0` 

But I can't find this hash on TaskCluster index.

**Comment by lissyx** [comment]
So far I'm:
 - changing back `trust-domain` to `gecko`
 - hacking the mach artifact command to fetch from latest:
```
diff --git a/python/mozbuild/mozbuild/artifact_commands.py b/python/mozbuild/mozbuild/artifact_commands.py
index 3128f967f310..a6e191f365ad 100644
--- a/python/mozbuild/mozbuild/artifact_commands.py
+++ b/python/mozbuild/mozbuild/artifact_commands.py
@@ -325,9 +325,15 @@ class PackageFrontend(MachCommandBase):
                     self.log(logging.ERROR, 'artifact', {'build': user_value},
                              'Could not find a toolchain build named `{build}`')
                     return 1
+                print('task:', task)
+
+                index_search = task.optimization.get('index-search', [])
+                if len(index_search) == 1:
+                    base_idx = '.'.join(index_search[0].split('.')[:-2] + ['latest'])
+                index_search += [ base_idx ]
 
                 task_id = IndexSearch().should_replace_task(
-                    task, {}, task.optimization.get('index-search', []))
+                    task, {}, index_search)
                 artifact_name = task.attributes.get('toolchain-artifact')
                 if task_id in (True, False) or not artifact_name:
                     self.log(logging.ERROR, 'artifact', {'build': user_value},
```

**Comment by gbrownmozilla** [comment]
Is this a variation on https://bugzilla.mozilla.org/show_bug.cgi?id=1636797? Does 'mach clobber python' help?

**Comment by lissyx** [comment]
> Is this a variation on https://bugzilla.mozilla.org/show_bug.cgi?id=1636797? Does 'mach clobber python' help?

I doubt, I've tried:
 - rm -fr objdir
 - mach clobber
 - mach clobber python
 - git clean -fdx

**Comment by lissyx** [comment]
Taken care of
