### ISSUE TITLE
Taskcluster config needs to point to the kaios project branch

### ISSUE THREAD

**Issue by EricRahm** [kaiostech/gecko-b2g#26]
We need to modify the URL used by taskcluster to calculate changes so that it uses our project branch. This reduces decision task times from 30 minutes to 6 minutes.

Please land the patch from [D83718](https://phabricator.services.mozilla.com/D83718): https://d3kxowhw4s8amj.cloudfront.net/file/data/hzwljt2q2xdkayzxt2lb/PHID-FILE-jy7ktxjsyo4a6iaxgb63/D83718.diff

**Comment by fabricedesre** [comment]
Pushed in https://github.com/kaiostech/gecko-b2g/commit/f2d5905ffac36638dad37f91c8d7b679c60584dc
