### ISSUE TITLE
Current build is broken missing nsPIDOMWindow

### ISSUE THREAD

**Issue by brendandahl** [kaiostech/gecko-b2g#29]
Building the x86_64 emulator was broken for me:

Needs:
https://hg.mozilla.org/projects/kaios-try/rev/69f28115cf7784c056b352eddadd4f4d9857f045

**Comment by fabricedesre** [comment]
Fixed in https://github.com/kaiostech/gecko-b2g/commit/7625016d7f9dd2f3bddb8d4bcc31bb014dcfb763
