### ISSUE TITLE
[emu-10-x86_64] Gonk FMRadio build failure

### ISSUE THREAD

**Issue by lissyx** [kaiostech/gecko-b2g#3]
with current HEAD @ e6f9cbbefe7e0c4e6820fbe68f6e678abfbde7bd
```
hal/gonk/GonkFMRadio.cpp:487:22: error: cast from pointer to smaller type 'int' loses information
```

**Comment by lissyx** [comment]
Seems like it's well-known clang-emitted C++ compiler warning when casting 64-bits pointer to 32-bits sized int.

**Comment by lissyx** [comment]
Other implems might suffer as well (but I can't build for them):
`hal/gonk/mtk_fm/GonkFMRadio.cpp`
`hal/gonk/sprd_fm/GonkFMRadio.cpp`

**Comment by fabricedesre** [comment]
fixed in https://github.com/kaiostech/gecko-b2g/commit/2b2d589527583455aa1eb5ad0ddfb1754a18d05a
