### ISSUE TITLE
Apply taskcluster changes to enable building in automation

### ISSUE THREAD

**Issue by EricRahm** [kaiostech/gecko-b2g#30]
[D82055](https://phabricator.services.mozilla.com/D82055) adds support for fully running kaios tasks in automation. Please apply the [exported patch](https://paste.mozilla.org/eiGLdZwW) with `curl https://paste.mozilla.org/eiGLdZwW/raw | git am -`.

**Comment by fabricedesre** [comment]
merged in https://github.com/kaiostech/gecko-b2g/commit/636194255863f1387a52f39f629e11be00aed713
