### ISSUE TITLE
Is this repository for the same operating system of Nokia 2720 Flip? 

### ISSUE THREAD

**Issue by BoQsc** [kaiostech/gecko-b2g#53]
Is this Kaios of Nokia 2720 Flip phone?

**Comment by fabricedesre** [comment]
The b2g48 branch is the one matching the Nokia 2720

**Comment by BoQsc** [comment]
> The b2g48 branch is the one matching the Nokia 2720

Thank you, @fabricedesre.

Quick link: [b2g48 branch](../tree/b2g48)

**Comment by BoQsc** [comment]
Some Review of KaiOS for Nokia 2720: https://youtu.be/slcscMxN4YA?t=44

Some other Review: https://www.youtube.com/watch?v=MVsEolc-LQA

One more Review: https://www.youtube.com/watch?v=5QMYoWj8giA

### Quality ones
Some more Review: https://www.youtube.com/watch?v=s5zEbhy_R7E

Tips and Tutorial: https://www.youtube.com/watch?v=cNQVudHnXCI
