### ISSUE TITLE
Accessing camera on a kaios device

### ISSUE THREAD

**Issue by den-ii** [kaiostech/gecko-b2g#61]
I am currently trying to access camera on a kaios device. [The kaios docs](https://developer.kaiostech.com/docs/sfp-3.0/api/next-new-apis/b2g/cameras/navigator-b2g-cameras/) noted it is accessible by `navigator.b2g` but it's not , apparently b2g was discontinued. I've also tried the normal browser way of accessing cameras but it shows a SecurityError when I try to do that. 
![ex1](https://github.com/kaiostech/gecko-b2g/assets/104834114/0bdfc228-4211-45d7-bea6-9eb1b6b519ef)

**Comment by strukturart** [comment]
Have you already tried it ?https://github.com/strukturart/passport/blob/1a6d64837e4a17c1bf5e63bb7ab0137fcb82fb01/application/assets/js/scan.js#L14

**Comment by juicio8** [comment]
Just did. I'm getting SecurityError

**Comment by shawnjohnjr** [comment]
What KaiOS device are you testing with? Which version do you test with? How do you attach js console?

**Comment by den-ii** [comment]
> Just did. I'm getting SecurityError

I cloned passport repo and tested it on the device, the camera works. I'll keep trying

**Comment by den-ii** [comment]
> Have you already tried it ?https://github.com/strukturart/passport/blob/1a6d64837e4a17c1bf5e63bb7ab0137fcb82fb01/application/assets/js/scan.js#L14

Thanks, https://github.com/strukturart/passport/blob/1a6d64837e4a17c1bf5e63bb7ab0137fcb82fb01/application/assets/js/mozactivity.js this works to access the camera. I'm still trying to figure out how scan.js and mozactivity.js go together. The camera in passport is accessed and styled. Using just mozActivity takes me to the camera app

**Comment by den-ii** [comment]
@strukturart . I will have to really study your code, but if you're less busy maybe you could help me out

**Comment by den-ii** [comment]
@shawnjohnjr . I'm using a kaios phone, and accessing the console with firefox, when the device is plugged to the laptop, I'm able to install the package app on the device and access the console, just like kaios docs says
.

**Comment by strukturart** [comment]
> @strukturart . I will have to really study your code, but if you're less busy maybe you could help me out

what do you want to know ?

**Comment by den-ii** [comment]
@strukturart What does mozActivity.js do exactly, how does it combine with scan.js. I want to be able to access the camera/video, and capture. I also want to be able to style it, like you did.

**Comment by strukturart** [comment]
mozactivity is a collection of mozActivity/web
Activity which I often use in my apps. mozActivity is used to open other apps and use their functions for your app. with photo() you can use the KaiOS photo app. scan.js is a qr code scanner which I use to make data entry easier for users.

**Comment by strukturart** [comment]
If you share your code I can help you in more detail.

**Comment by den-ii** [comment]
Okay, is it okay to mail you? This is your email right? print@strukturart.com

**Comment by shawnjohnjr** [comment]
Could you confirm your KaiOS version? 2.5 and 3.0 API is so different, and navigator.b2g only works for 3.0.

**Comment by den-ii** [comment]
It's 2.5. So it works on version 3.0? Seems 3.0 would be way easy

**Comment by strukturart** [comment]
> Okay, is it okay to mail you? This is your email right? [print@strukturart.com](mailto:print@strukturart.com)

yes

**Comment by strukturart** [comment]
> It's 2.5. So it works on version 3.0? Seems 3.0 would be way easy

some APIs are not backwards compatible

**Comment by den-ii** [comment]
Okay, The error is because I'm using react. Camera access works well with vanilla js

**Comment by den-ii** [comment]
Okay, it works, `navigator.mediaDevices.getUserMedia works!`. It was from my side, I wasn't uninstalling the app when re-installing it, that's why I thought it didn't work in react. The security issue was because the type wasn't sent to packaged, and I think the manifest files were'nt updating when re-installing.
