### ISSUE TITLE
[emu-10-x86_64] WASM-related linkage error

### ISSUE THREAD

**Issue by lissyx** [kaiostech/gecko-b2g#7]
Likely a regression from 21e6e3e6146e589cba98ec1fa66801c108547e85, since adding the same flag on non-b2g-desktop mozconfig fixes.

**Comment by fabricedesre** [comment]
Fixed in https://github.com/kaiostech/gecko-b2g/commit/85d5a5c8432df99dc708c2b099a90e6e78f99a27
